// SPDX-License-Identifier: MIT

// SPDX-FileCopyrightText: 2024 Stefan Schmidt


// FIXME: Doxygen all this
// FIXME: Formatting

#ifndef __XINPUT_XINPUT_H__
#define __XINPUT_XINPUT_H__

#ifdef __cplusplus
extern "C" {
#endif

// FIXME doxygen here
// Bitmask of the digital buttons, a set bit indicated that the corresponding button is pressed
#define NXDK_XINPUT_GAMEPAD_DIGITAL_DPAD_UP ((WORD)0x0001)
#define NXDK_XINPUT_GAMEPAD_DIGITAL_DPAD_DOWN ((WORD)0x0002)
#define NXDK_XINPUT_GAMEPAD_DIGITAL_DPAD_LEFT ((WORD)0x0004)
#define NXDK_XINPUT_GAMEPAD_DIGITAL_DPAD_RIGHT ((WORD)0x0008)
#define NXDK_XINPUT_GAMEPAD_DIGITAL_START ((WORD)0x0010)
#define NXDK_XINPUT_GAMEPAD_DIGITAL_BACK ((WORD)0x0020)
#define NXDK_XINPUT_GAMEPAD_DIGITAL_LEFT_THUMB ((WORD)0x0040)
#define NXDK_XINPUT_GAMEPAD_DIGITAL_RIGHT_THUMB ((WORD)0x0080)
#define NXDK_XINPUT_GAMEPAD_DIGITAL_LEFT_SHOULDER ((WORD)0x0100)
#define NXDK_XINPUT_GAMEPAD_DIGITAL_RIGHT_SHOULDER ((WORD)0x0200)
#define NXDK_XINPUT_GAMEPAD_DIGITAL_A ((WORD)0x1000)
#define NXDK_XINPUT_GAMEPAD_DIGITAL_B ((WORD)0x2000)
#define NXDK_XINPUT_GAMEPAD_DIGITAL_X ((WORD)0x4000)
#define NXDK_XINPUT_GAMEPAD_DIGITAL_Y ((WORD)0x8000)
#define NXDK_XINPUT_GAMEPAD_DIGITAL_WHITE NXDK_XINPUT_GAMEPAD_DIGITAL_LEFT_SHOULDER
#define NXDK_XINPUT_GAMEPAD_DIGITAL_BLACK NXDK_XINPUT_GAMEPAD_DIGITAL_RIGHT_SHOULDER

// FIXME: XDK-defs. INCOMPATIBLE!
// offsets for bAnalogButtons
#define NXDK_XINPUT_GAMEPAD_ANALOG_A 0
#define NXDK_XINPUT_GAMEPAD_ANALOG_B 1
#define NXDK_XINPUT_GAMEPAD_ANALOG_X 2
#define NXDK_XINPUT_GAMEPAD_ANALOG_Y 3
#define NXDK_XINPUT_GAMEPAD_ANALOG_BLACK 4
#define NXDK_XINPUT_GAMEPAD_ANALOG_WHITE 5
#define NXDK_XINPUT_GAMEPAD_ANALOG_LEFT_TRIGGER 6
#define NXDK_XINPUT_GAMEPAD_ANALOG_RIGHT_TRIGGER 7
#define NXDK_XINPUT_GAMEPAD_ANALOG_LEFT_SHOULDER NXDK_XINPUT_GAMEPAD_ANALOG_WHITE
#define NXDK_XINPUT_GAMEPAD_ANALOG_RIGHT_SHOULDER NXDK_XINPUT_GAMEPAD_ANALOG_BLACK

#if defined(NXDK_XINPUT_XDK_COMPAT) && defined(NXDK_XINPUT_WIN32_COMPAT)
    #error "Both NXDK_XINPUT_XDK_COMPAT and NXDK_XINPUT_WIN32_COMPAT are defined. Only one must be defined!"
#elif defined(NXDK_XINPUT_XDK_COMPAT)
#define XINPUT_GAMEPAD_DPAD_UP NXDK_XINPUT_GAMEPAD_DIGITAL_DPAD_UP
#define XINPUT_GAMEPAD_DPAD_DOWN NXDK_XINPUT_GAMEPAD_DIGITAL_DPAD_DOWN
#define XINPUT_GAMEPAD_DPAD_LEFT NXDK_XINPUT_GAMEPAD_DIGITAL_DPAD_LEFT
#define XINPUT_GAMEPAD_DPAD_RIGHT NXDK_XINPUT_GAMEPAD_DIGITAL_DPAD_RIGHT
#define XINPUT_GAMEPAD_DPAD_START NXDK_XINPUT_GAMEPAD_DIGITAL_DPAD_START
#define XINPUT_GAMEPAD_DPAD_BACK NXDK_XINPUT_GAMEPAD_DIGITAL_DPAD_BACK
#define XINPUT_GAMEPAD_LEFT_THUMB NXDK_XINPUT_GAMEPAD_DIGITAL_LEFT_THUMB
#define XINPUT_GAMEPAD_RIGHT_THUMB NXDK_XINPUT_GAMEPAD_DIGITAL_RIGHT_THUMB
#define XINPUT_GAMEPAD_A NXDK_XINPUT_GAMEPAD_ANALOG_A
#define XINPUT_GAMEPAD_B NXDK_XINPUT_GAMEPAD_ANALOG_B
#define XINPUT_GAMEPAD_X NXDK_XINPUT_GAMEPAD_ANALOG_X
#define XINPUT_GAMEPAD_Y NXDK_XINPUT_GAMEPAD_ANALOG_Y
#define XINPUT_GAMEPAD_BLACK NXDK_XINPUT_GAMEPAD_ANALOG_BLACK
#define XINPUT_GAMEPAD_WHITE NXDK_XINPUT_GAMEPAD_ANALOG_WHITE
#define XINPUT_GAMEPAD_LEFT_TRIGGER NXDK_XINPUT_GAMEPAD_ANALOG_LEFT_TRIGGER
#define XINPUT_GAMEPAD_RIGHT_TRIGGER NXDK_XINPUT_GAMEPAD_ANALOG_RIGHT_TRIGGER
#elif defined(NXDK_XINPUT_WIN32_COMPAT)
#define XINPUT_GAMEPAD_DPAD_UP NXDK_XINPUT_GAMEPAD_DIGITAL_DPAD_UP
#define XINPUT_GAMEPAD_DPAD_DOWN NXDK_XINPUT_GAMEPAD_DIGITAL_DPAD_DOWN
#define XINPUT_GAMEPAD_DPAD_LEFT NXDK_XINPUT_GAMEPAD_DIGITAL_DPAD_LEFT
#define XINPUT_GAMEPAD_DPAD_RIGHT NXDK_XINPUT_GAMEPAD_DIGITAL_DPAD_RIGHT
#define XINPUT_GAMEPAD_DPAD_START NXDK_XINPUT_GAMEPAD_DIGITAL_DPAD_START
#define XINPUT_GAMEPAD_DPAD_BACK NXDK_XINPUT_GAMEPAD_DIGITAL_DPAD_BACK
#define XINPUT_GAMEPAD_LEFT_THUMB NXDK_XINPUT_GAMEPAD_DIGITAL_LEFT_THUMB
#define XINPUT_GAMEPAD_RIGHT_THUMB NXDK_XINPUT_GAMEPAD_DIGITAL_RIGHT_THUMB
#define XINPUT_GAMEPAD_A NXDK_XINPUT_GAMEPAD_DIGITAL_A
#define XINPUT_GAMEPAD_B NXDK_XINPUT_GAMEPAD_DIGITAL_B
#define XINPUT_GAMEPAD_X NXDK_XINPUT_GAMEPAD_DIGITAL_X
#define XINPUT_GAMEPAD_Y NXDK_XINPUT_GAMEPAD_DIGITAL_Y
#define XINPUT_GAMEPAD_BLACK NXDK_XINPUT_GAMEPAD_DIGITAL_BLACK
#define XINPUT_GAMEPAD_WHITE NXDK_XINPUT_GAMEPAD_DIGITAL_WHITE
#define XINPUT_GAMEPAD_LEFT_TRIGGER NXDK_XINPUT_GAMEPAD_DIGITAL_LEFT_TRIGGER
#define XINPUT_GAMEPAD_RIGHT_TRIGGER NXDK_XINPUT_GAMEPAD_DIGITAL_RIGHT_TRIGGER
#endif

typedef struct _XINPUT_GAMEPAD
{
    WORD wButtons;
    BYTE bAnalogButtons[8];
    SHORT sThumbLX;
    SHORT sThumbLY;
    SHORT sThumbRX;
    SHORT sThumbRY;
    BYTE bLeftTrigger; // Non-XDK addition
    BYTE bRightTrigger; // Non-XDK addition
} XINPUT_GAMEPAD, *PXINPUT_GAMEPAD;



#ifdef __cplusplus
}
#endif

#endif
