name: Build Docker image

on: [push, pull_request]

jobs:
  main:
    name: Docker
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        image-name: [nxdk, nxdk-debug]
        include:
          - image-name: nxdk
            build-args: buildparams=CFLAGS="-O2 -flto -ffat-lto-objects" CXXFLAGS="-O2 -flto -ffat-lto-objects" ASFLAGS="-O2 -flto -ffat-lto-objects"
            tag: latest
          - image-name: nxdk-debug
            build-args: buildparams=DEBUG=y
            tag: debug
    steps:
      - name: Clone Tree
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          submodules: recursive
      - name: Set variables
        run: |
          echo "DOCKER_TAG=$(echo ghcr.io/${{ github.repository }}:${{ matrix.tag }}|tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "CREATED=$(date --rfc-3339=seconds --utc)" >> $GITHUB_ENV
          echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
      - name: Build Docker image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          load: true
          push: false
          tags: ${{ env.DOCKER_TAG}}
          build-args: ${{ matrix.build-args }}
      - name: Test Docker image
        run: |
          cd samples
          for dir in */
          do
            cd "$dir"
            docker run --rm -v `pwd`:/usr/src/app -t "${DOCKER_TAG}" make -j`nproc`
            cd ..
          done
      - name: Test Docker image with LTO
        if: matrix.tag == 'latest'
        run: |
          cd samples
          sudo git clean -xf . >/dev/null
          for dir in */
          do
            cd "$dir"
            docker run --rm -v `pwd`:/usr/src/app -t "${DOCKER_TAG}" make -j`nproc` CFLAGS="-O2 -flto -ffat-lto-objects" CXXFLAGS="-O2 -flto -ffat-lto-objects" LDFLAGS="-fat-lto-objects"
            cd ..
          done

      - name: Login to Docker Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        if: github.ref == 'refs/heads/master'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker Image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        if: github.ref == 'refs/heads/master' && matrix.tag == 'latest'
        with:
          push: true
          build-args: ${{ matrix.build-args }}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ env.CREATED }}
          tags: ${{ env.DOCKER_TAG }}

      - name: Push to XboxDev Group
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        if: github.repository_owner == 'XboxDev' && github.ref == 'refs/heads/master'
        with:
          push: true
          build-args: ${{ matrix.build-args }}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ env.CREATED }}
          tags: |
            ghcr.io/xboxdev/${{ matrix.image-name }}:latest
            ghcr.io/xboxdev/${{ matrix.image-name }}:git-${{ env.SHORT_SHA }}

      - name: Login to Docker Hub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        if: github.repository_owner == 'XboxDev' && github.ref == 'refs/heads/master'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        if: github.repository_owner == 'XboxDev' && github.ref == 'refs/heads/master'
        with:
          push: true
          build-args: ${{ matrix.build-args }}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ env.CREATED }}
          tags: |
            xboxdev/${{ matrix.image-name }}:latest
            xboxdev/${{ matrix.image-name }}:git-${{ env.SHORT_SHA }}
